/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RouteCheckerRouteImport } from './routes/route-checker'
import { Route as NearMeRouteImport } from './routes/near-me'
import { Route as MapRouteImport } from './routes/map'
import { Route as FineCalculatorRouteImport } from './routes/fine-calculator'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteCheckerRoute = RouteCheckerRouteImport.update({
  id: '/route-checker',
  path: '/route-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const NearMeRoute = NearMeRouteImport.update({
  id: '/near-me',
  path: '/near-me',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const FineCalculatorRoute = FineCalculatorRouteImport.update({
  id: '/fine-calculator',
  path: '/fine-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fine-calculator': typeof FineCalculatorRoute
  '/map': typeof MapRoute
  '/near-me': typeof NearMeRoute
  '/route-checker': typeof RouteCheckerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fine-calculator': typeof FineCalculatorRoute
  '/map': typeof MapRoute
  '/near-me': typeof NearMeRoute
  '/route-checker': typeof RouteCheckerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fine-calculator': typeof FineCalculatorRoute
  '/map': typeof MapRoute
  '/near-me': typeof NearMeRoute
  '/route-checker': typeof RouteCheckerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fine-calculator'
    | '/map'
    | '/near-me'
    | '/route-checker'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fine-calculator'
    | '/map'
    | '/near-me'
    | '/route-checker'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/fine-calculator'
    | '/map'
    | '/near-me'
    | '/route-checker'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FineCalculatorRoute: typeof FineCalculatorRoute
  MapRoute: typeof MapRoute
  NearMeRoute: typeof NearMeRoute
  RouteCheckerRoute: typeof RouteCheckerRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-checker': {
      id: '/route-checker'
      path: '/route-checker'
      fullPath: '/route-checker'
      preLoaderRoute: typeof RouteCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/near-me': {
      id: '/near-me'
      path: '/near-me'
      fullPath: '/near-me'
      preLoaderRoute: typeof NearMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fine-calculator': {
      id: '/fine-calculator'
      path: '/fine-calculator'
      fullPath: '/fine-calculator'
      preLoaderRoute: typeof FineCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FineCalculatorRoute: FineCalculatorRoute,
  MapRoute: MapRoute,
  NearMeRoute: NearMeRoute,
  RouteCheckerRoute: RouteCheckerRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
